framework:
    messenger:
        transports:
            microservices:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        microservices:
                            binding_keys: [microservices]
            sync: 'sync://'
                
        routing:
            App\Message\MicroServicesMessage: sync
            App\Message\RemoveApiKey: sync
            App\Message\UpdateApiKey: sync
            App\Message\CreateClip: sync
            App\Message\CreateVideo: sync
            'App\Protobuf\MicroServicesMessage': microservices
