framework:
    messenger:
        transports:
            microservices:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: microservices
                        type: direct
                    auto_setup: true
                    queues:
                        sound_extractor:
                            binding_keys: [sound_extractor]
                        subtitle_generator:
                            binding_keys: [subtitle_generator]
                        subtitle_merger:
                            binding_keys: [subtitle_merger]
                        subtitle_transformer:
                            binding_keys: [subtitle_transformer]
                        video_formatter:
                            binding_keys: [video_formatter]
                        subtitle_incrustator:
                            binding_keys: [subtitle_incrustator]
                        video_incrustator:
                            binding_keys: [video_incrustator]
                        video_splitter:
                            binding_keys: [video_splitter]
                        api:
                            binding_keys: [api]
            sync: 'sync://'
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async:
                            binding_keys: [async]
                
        routing:
            App\UseCase\Command\UploadTikTokClip: async
            App\UseCase\Command\UploadTikTokVideo: async
            App\UseCase\Command\UploadTikTokVideoStatus: async

            App\UseCase\Command\CreateClip: sync
            App\UseCase\Command\CreateVideo: sync
            App\UseCase\Command\UpdateTikTokToken: sync
            App\UseCase\Command\UpdateVideoPublishStatus: sync
            App\UseCase\Command\UpdateClipStatus: sync

            App\Message\TaskMessage: sync

            'App\Protobuf\TaskMessage': microservices
            'App\Protobuf\SoundExtractorMessage': microservices
            'App\Protobuf\SubtitleGeneratorMessage': microservices
            'App\Protobuf\SubtitleMergerMessage': microservices
            'App\Protobuf\SubtitleTransformerMessage': microservices
            'App\Protobuf\VideoFormatterMessage': microservices
            'App\Protobuf\SubtitleIncrustatorMessage': microservices
