framework:
    messenger:
        transports:
            microservices:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: App\Messenger\Serializer\ProtobufSerializer
                options:
                    exchange:
                        name: microservices
                        type: direct
                    auto_setup: true
                    queues:
                        sound_extractor:
                            binding_keys: [sound_extractor]
                        subtitle_generator:
                            binding_keys: [subtitle_generator]
                        subtitle_merger:
                            binding_keys: [subtitle_merger]
                        subtitle_transformer:
                            binding_keys: [subtitle_transformer]
                        subtitle_incrustator:
                            binding_keys: [subtitle_incrustator]
                        video_formatter:
                            binding_keys: [video_formatter]
                        video_incrustator:
                            binding_keys: [video_incrustator]
                        video_splitter:
                            binding_keys: [video_splitter]
                        api:
                            binding_keys: [api]
            sync: 'sync://'
                
        routing:
            App\Message\ServicesMessage: sync
            App\Message\RemoveApiKey: sync
            App\Message\UpdateApiKey: sync
            App\Message\CreateClip: sync
            App\Message\CreateVideo: sync
            'App\Protobuf\ServicesMessage': microservices
            'App\Protobuf\SoundExtractorMessage': microservices
            'App\Protobuf\SubtitleGeneratorMessage': microservices
            'App\Protobuf\SubtitleMergerMessage': microservices
            'App\Protobuf\SubtitleTransformerMessage': microservices
            'App\Protobuf\SubtitleIncrustatorMessage': microservices
