framework:
    messenger:
        transports:
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async:
                            binding_keys: [async]
            sync: 'sync://'
                
        routing:
            App\Message\RemoveApiKey: sync
            App\Message\UpdateApiKey: sync
            App\Message\CreateClip: sync
