security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        api_provider:
            id: App\Security\ApiProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            custom_authenticator:
                - App\Security\ApiAuthenticator
            pattern: ^/(api)(?!/docs)
            stateless: true
            provider: api_provider
    access_control:
        - { path: ^/api/tiktok/callback, roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/token, roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api/status, roles: PUBLIC_ACCESS, methods: GET }
        - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
