framework:
    workflows:
        clip:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Clip
            initial_marking: UPLOADED
            places:
                - UPLOADED
                - SOUND_EXTRACTOR_PENDING
                - SOUND_EXTRACTOR_COMPLETE
                - SOUND_EXTRACTOR_ERROR
                - SUBTITLE_GENERATOR_PENDING
                - SUBTITLE_GENERATOR_COMPLETE
                - SUBTITLE_GENERATOR_ERROR
            transitions:
                process_sound_extractor:
                    from: UPLOADED
                    to: SOUND_EXTRACTOR_PENDING
                sound_extraction_success:
                    from: SOUND_EXTRACTOR_PENDING
                    to: SOUND_EXTRACTOR_COMPLETE
                sound_extraction_failure:
                    from: SOUND_EXTRACTOR_PENDING
                    to: SOUND_EXTRACTOR_ERROR

                process_subtitle_generator:
                    from: SOUND_EXTRACTOR_COMPLETE
                    to: SUBTITLE_GENERATOR_PENDING
                subtitle_generator_success:
                    from: SUBTITLE_GENERATOR_PENDING
                    to: SUBTITLE_GENERATOR_COMPLETE
                subtitle_generator_failure:
                    from: SUBTITLE_GENERATOR_PENDING
                    to: SUBTITLE_GENERATOR_ERROR

                process_subtitle_merger:
                    from: SUBTITLE_GENERATOR_COMPLETE
                    to: SUBTITLE_MERGER_PENDING
                subtitle_merger_success:
                    from: SUBTITLE_MERGER_PENDING
                    to: SUBTITLE_MERGER_COMPLETE
                subtitle_merger_failure:
                    from: SUBTITLE_MERGER_PENDING
                    to: SUBTITLE_MERGER_ERROR

                process_subtitle_transformer:
                    from: SUBTITLE_MERGER_COMPLETE
                    to: SUBTITLE_TRANSFORMER_PENDING
                subtitle_transformer_success:
                    from: SUBTITLE_TRANSFORMER_PENDING
                    to: SUBTITLE_TRANSFORMER_COMPLETE
                subtitle_transformer_failure:
                    from: SUBTITLE_TRANSFORMER_PENDING
                    to: SUBTITLE_TRANSFORMER_ERROR