<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Clip</code>
 */
class Clip extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     */
    protected $userId = '';
    /**
     * Generated from protobuf field <code>string status = 3;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>
     */
    protected $originalVideo = null;
    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     */
    protected $cover = '';
    /**
     * Generated from protobuf field <code>.App.Protobuf.Configuration configuration = 6;</code>
     */
    protected $configuration = null;
    /**
     * Generated from protobuf field <code>optional .App.Protobuf.Video processedVideo = 7;</code>
     */
    protected $processedVideo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $userId
     *     @type string $status
     *     @type \App\Protobuf\Video $originalVideo
     *     @type string $cover
     *     @type \App\Protobuf\Configuration $configuration
     *     @type \App\Protobuf\Video $processedVideo
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>
     * @return \App\Protobuf\Video|null
     */
    public function getOriginalVideo()
    {
        return $this->originalVideo;
    }

    public function hasOriginalVideo()
    {
        return isset($this->originalVideo);
    }

    public function clearOriginalVideo()
    {
        unset($this->originalVideo);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>
     * @param \App\Protobuf\Video $var
     * @return $this
     */
    public function setOriginalVideo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuf\Video::class);
        $this->originalVideo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCover($var)
    {
        GPBUtil::checkString($var, True);
        $this->cover = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Configuration configuration = 6;</code>
     * @return \App\Protobuf\Configuration|null
     */
    public function getConfiguration()
    {
        return $this->configuration;
    }

    public function hasConfiguration()
    {
        return isset($this->configuration);
    }

    public function clearConfiguration()
    {
        unset($this->configuration);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Configuration configuration = 6;</code>
     * @param \App\Protobuf\Configuration $var
     * @return $this
     */
    public function setConfiguration($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuf\Configuration::class);
        $this->configuration = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .App.Protobuf.Video processedVideo = 7;</code>
     * @return \App\Protobuf\Video|null
     */
    public function getProcessedVideo()
    {
        return $this->processedVideo;
    }

    public function hasProcessedVideo()
    {
        return isset($this->processedVideo);
    }

    public function clearProcessedVideo()
    {
        unset($this->processedVideo);
    }

    /**
     * Generated from protobuf field <code>optional .App.Protobuf.Video processedVideo = 7;</code>
     * @param \App\Protobuf\Video $var
     * @return $this
     */
    public function setProcessedVideo($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuf\Video::class);
        $this->processedVideo = $var;

        return $this;
    }

}

