<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Clip</code>.
 */
class Clip extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>.
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string userId = 2;</code>.
     */
    protected $userId = '';
    /**
     * Generated from protobuf field <code>string status = 3;</code>.
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>.
     */
    protected $originalVideo;
    /**
     * Generated from protobuf field <code>string cover = 5;</code>.
     */
    protected $cover = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var string $id
     * @var string $userId
     * @var string $status
     * @var Video  $originalVideo
     * @var string $cover
     *             }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>.
     *
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>.
     *
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Generated from protobuf field <code>string userId = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setUserId($var)
    {
        GPBUtil::checkString($var, true);
        $this->userId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>.
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, true);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>.
     *
     * @return Video|null
     */
    public function getOriginalVideo()
    {
        return $this->originalVideo;
    }

    public function hasOriginalVideo()
    {
        return isset($this->originalVideo);
    }

    public function clearOriginalVideo()
    {
        unset($this->originalVideo);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Video originalVideo = 4;</code>.
     *
     * @param Video $var
     *
     * @return $this
     */
    public function setOriginalVideo($var)
    {
        GPBUtil::checkMessage($var, Video::class);
        $this->originalVideo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>.
     *
     * @return string
     */
    public function getCover()
    {
        return $this->cover;
    }

    /**
     * Generated from protobuf field <code>string cover = 5;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setCover($var)
    {
        GPBUtil::checkString($var, true);
        $this->cover = $var;

        return $this;
    }
}
