<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Configuration</code>
 */
class Configuration extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string subtitleFont = 2;</code>
     */
    protected $subtitleFont = '';
    /**
     * Generated from protobuf field <code>string subtitleSize = 3;</code>
     */
    protected $subtitleSize = '';
    /**
     * Generated from protobuf field <code>string subtitleColor = 4;</code>
     */
    protected $subtitleColor = '';
    /**
     * Generated from protobuf field <code>string subtitleBold = 5;</code>
     */
    protected $subtitleBold = '';
    /**
     * Generated from protobuf field <code>string subtitleItalic = 6;</code>
     */
    protected $subtitleItalic = '';
    /**
     * Generated from protobuf field <code>string subtitleUnderline = 7;</code>
     */
    protected $subtitleUnderline = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 8;</code>
     */
    protected $subtitleOutlineColor = '';
    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 9;</code>
     */
    protected $subtitleOutlineThickness = '';
    /**
     * Generated from protobuf field <code>string subtitleShadow = 10;</code>
     */
    protected $subtitleShadow = '';
    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 11;</code>
     */
    protected $subtitleShadowColor = '';
    /**
     * Generated from protobuf field <code>string format = 12;</code>
     */
    protected $format = '';
    /**
     * Generated from protobuf field <code>string split = 13;</code>
     */
    protected $split = '';
    /**
     * Generated from protobuf field <code>string marginV = 14;</code>
     */
    protected $marginV = '';
    /**
     * Generated from protobuf field <code>string privacyOptions = 15;</code>
     */
    protected $privacyOptions = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $subtitleFont
     *     @type string $subtitleSize
     *     @type string $subtitleColor
     *     @type string $subtitleBold
     *     @type string $subtitleItalic
     *     @type string $subtitleUnderline
     *     @type string $subtitleOutlineColor
     *     @type string $subtitleOutlineThickness
     *     @type string $subtitleShadow
     *     @type string $subtitleShadowColor
     *     @type string $format
     *     @type string $split
     *     @type string $marginV
     *     @type string $privacyOptions
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 2;</code>
     * @return string
     */
    public function getSubtitleFont()
    {
        return $this->subtitleFont;
    }

    /**
     * Generated from protobuf field <code>string subtitleFont = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleFont($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleFont = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 3;</code>
     * @return string
     */
    public function getSubtitleSize()
    {
        return $this->subtitleSize;
    }

    /**
     * Generated from protobuf field <code>string subtitleSize = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleSize($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleSize = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 4;</code>
     * @return string
     */
    public function getSubtitleColor()
    {
        return $this->subtitleColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleColor = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleBold = 5;</code>
     * @return string
     */
    public function getSubtitleBold()
    {
        return $this->subtitleBold;
    }

    /**
     * Generated from protobuf field <code>string subtitleBold = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleBold($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleBold = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleItalic = 6;</code>
     * @return string
     */
    public function getSubtitleItalic()
    {
        return $this->subtitleItalic;
    }

    /**
     * Generated from protobuf field <code>string subtitleItalic = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleItalic($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleItalic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleUnderline = 7;</code>
     * @return string
     */
    public function getSubtitleUnderline()
    {
        return $this->subtitleUnderline;
    }

    /**
     * Generated from protobuf field <code>string subtitleUnderline = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleUnderline($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleUnderline = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 8;</code>
     * @return string
     */
    public function getSubtitleOutlineColor()
    {
        return $this->subtitleOutlineColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineColor = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleOutlineColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleOutlineColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 9;</code>
     * @return string
     */
    public function getSubtitleOutlineThickness()
    {
        return $this->subtitleOutlineThickness;
    }

    /**
     * Generated from protobuf field <code>string subtitleOutlineThickness = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleOutlineThickness($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleOutlineThickness = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 10;</code>
     * @return string
     */
    public function getSubtitleShadow()
    {
        return $this->subtitleShadow;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadow = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleShadow($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleShadow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 11;</code>
     * @return string
     */
    public function getSubtitleShadowColor()
    {
        return $this->subtitleShadowColor;
    }

    /**
     * Generated from protobuf field <code>string subtitleShadowColor = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitleShadowColor($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitleShadowColor = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string format = 12;</code>
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * Generated from protobuf field <code>string format = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->format = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string split = 13;</code>
     * @return string
     */
    public function getSplit()
    {
        return $this->split;
    }

    /**
     * Generated from protobuf field <code>string split = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setSplit($var)
    {
        GPBUtil::checkString($var, True);
        $this->split = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string marginV = 14;</code>
     * @return string
     */
    public function getMarginV()
    {
        return $this->marginV;
    }

    /**
     * Generated from protobuf field <code>string marginV = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setMarginV($var)
    {
        GPBUtil::checkString($var, True);
        $this->marginV = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string privacyOptions = 15;</code>
     * @return string
     */
    public function getPrivacyOptions()
    {
        return $this->privacyOptions;
    }

    /**
     * Generated from protobuf field <code>string privacyOptions = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivacyOptions($var)
    {
        GPBUtil::checkString($var, True);
        $this->privacyOptions = $var;

        return $this;
    }

}

