<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.SoundExtractorMessage</code>.
 */
class SoundExtractorMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>.
     */
    protected $clip;
    /**
     * Generated from protobuf field <code>string service = 2;</code>.
     */
    protected $service = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *                    Optional. Data for populating the Message object.
     *
     * @var Clip   $clip
     * @var string $service
     *             }
     */
    public function __construct($data = null)
    {
        GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>.
     *
     * @return Clip|null
     */
    public function getClip()
    {
        return $this->clip;
    }

    public function hasClip()
    {
        return isset($this->clip);
    }

    public function clearClip()
    {
        unset($this->clip);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>.
     *
     * @param Clip $var
     *
     * @return $this
     */
    public function setClip($var)
    {
        GPBUtil::checkMessage($var, Clip::class);
        $this->clip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service = 2;</code>.
     *
     * @return string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>string service = 2;</code>.
     *
     * @param string $var
     *
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkString($var, true);
        $this->service = $var;

        return $this;
    }
}
