<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.SubtitleMergerMessage</code>
 */
class SubtitleMergerMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>
     */
    protected $clip = null;
    /**
     * Generated from protobuf field <code>string service = 2;</code>
     */
    protected $service = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \App\Protobuf\Clip $clip
     *     @type string $service
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>
     * @return \App\Protobuf\Clip|null
     */
    public function getClip()
    {
        return $this->clip;
    }

    public function hasClip()
    {
        return isset($this->clip);
    }

    public function clearClip()
    {
        unset($this->clip);
    }

    /**
     * Generated from protobuf field <code>.App.Protobuf.Clip clip = 1;</code>
     * @param \App\Protobuf\Clip $var
     * @return $this
     */
    public function setClip($var)
    {
        GPBUtil::checkMessage($var, \App\Protobuf\Clip::class);
        $this->clip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string service = 2;</code>
     * @return string
     */
    public function getService()
    {
        return $this->service;
    }

    /**
     * Generated from protobuf field <code>string service = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setService($var)
    {
        GPBUtil::checkString($var, True);
        $this->service = $var;

        return $this;
    }

}

