<?php

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

namespace App\Protobuf;

/**
 * Protobuf type <code>App.Protobuf.VideoPublishStatus</code>.
 */
class VideoPublishStatus
{
    /**
     * Generated from protobuf enum <code>UPLOADING = 0;</code>.
     */
    public const UPLOADING = 0;
    /**
     * Generated from protobuf enum <code>PUBLISHED = 1;</code>.
     */
    public const PUBLISHED = 1;
    /**
     * Generated from protobuf enum <code>ERROR = 2;</code>.
     */
    public const ERROR = 2;

    private static $valueToName = [
        self::UPLOADING => 'UPLOADING',
        self::PUBLISHED => 'PUBLISHED',
        self::ERROR => 'ERROR',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no name defined for value %s', __CLASS__, $value));
        }

        return self::$valueToName[$value];
    }

    public static function value($name)
    {
        $const = __CLASS__.'::'.strtoupper($name);
        if (!defined($const)) {
            throw new \UnexpectedValueException(sprintf('Enum %s has no value defined for name %s', __CLASS__, $name));
        }

        return constant($const);
    }
}
