<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Message.proto

namespace App\Protobuf;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>App.Protobuf.Video</code>
 */
class Video extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string originalName = 2;</code>
     */
    protected $originalName = '';
    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     */
    protected $name = null;
    /**
     * Generated from protobuf field <code>string mimeType = 4;</code>
     */
    protected $mimeType = '';
    /**
     * Generated from protobuf field <code>optional int64 size = 5;</code>
     */
    protected $size = null;
    /**
     * Generated from protobuf field <code>optional int64 length = 6;</code>
     */
    protected $length = null;
    /**
     * Generated from protobuf field <code>optional string subtitle = 7;</code>
     */
    protected $subtitle = null;
    /**
     * Generated from protobuf field <code>optional string ass = 8;</code>
     */
    protected $ass = null;
    /**
     * Generated from protobuf field <code>repeated string subtitles = 9;</code>
     */
    private $subtitles;
    /**
     * Generated from protobuf field <code>repeated string audios = 10;</code>
     */
    private $audios;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $originalName
     *     @type string $name
     *     @type string $mimeType
     *     @type int|string $size
     *     @type int|string $length
     *     @type string $subtitle
     *     @type string $ass
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $subtitles
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $audios
     * }
     */
    public function __construct($data = NULL) {
        \App\Protobuf\GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string originalName = 2;</code>
     * @return string
     */
    public function getOriginalName()
    {
        return $this->originalName;
    }

    /**
     * Generated from protobuf field <code>string originalName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOriginalName($var)
    {
        GPBUtil::checkString($var, True);
        $this->originalName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     * Generated from protobuf field <code>optional string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mimeType = 4;</code>
     * @return string
     */
    public function getMimeType()
    {
        return $this->mimeType;
    }

    /**
     * Generated from protobuf field <code>string mimeType = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMimeType($var)
    {
        GPBUtil::checkString($var, True);
        $this->mimeType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 size = 5;</code>
     * @return int|string
     */
    public function getSize()
    {
        return isset($this->size) ? $this->size : 0;
    }

    public function hasSize()
    {
        return isset($this->size);
    }

    public function clearSize()
    {
        unset($this->size);
    }

    /**
     * Generated from protobuf field <code>optional int64 size = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int64 length = 6;</code>
     * @return int|string
     */
    public function getLength()
    {
        return isset($this->length) ? $this->length : 0;
    }

    public function hasLength()
    {
        return isset($this->length);
    }

    public function clearLength()
    {
        unset($this->length);
    }

    /**
     * Generated from protobuf field <code>optional int64 length = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLength($var)
    {
        GPBUtil::checkInt64($var);
        $this->length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string subtitle = 7;</code>
     * @return string
     */
    public function getSubtitle()
    {
        return isset($this->subtitle) ? $this->subtitle : '';
    }

    public function hasSubtitle()
    {
        return isset($this->subtitle);
    }

    public function clearSubtitle()
    {
        unset($this->subtitle);
    }

    /**
     * Generated from protobuf field <code>optional string subtitle = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setSubtitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->subtitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ass = 8;</code>
     * @return string
     */
    public function getAss()
    {
        return isset($this->ass) ? $this->ass : '';
    }

    public function hasAss()
    {
        return isset($this->ass);
    }

    public function clearAss()
    {
        unset($this->ass);
    }

    /**
     * Generated from protobuf field <code>optional string ass = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setAss($var)
    {
        GPBUtil::checkString($var, True);
        $this->ass = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string subtitles = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubtitles()
    {
        return $this->subtitles;
    }

    /**
     * Generated from protobuf field <code>repeated string subtitles = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubtitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->subtitles = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string audios = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudios()
    {
        return $this->audios;
    }

    /**
     * Generated from protobuf field <code>repeated string audios = 10;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudios($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->audios = $arr;

        return $this;
    }

}

