parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $rabbitMqTransportDsn: '%env(MESSENGER_TRANSPORT_DSN)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Fixtures\Provider\EmailProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\LastnameProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\FirstnameProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\PlainPasswordProvider:
        tags: ['nelmio_alice.faker.provider']

    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                use_path_style_endpoint: true
                credentials:
                    key: '%env(S3_ACCESS_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'
