parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $secretKey: '%env(JWT_PASSPHRASE)%'
            string $rabbitMqTransportDsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            string $tiktokClientKey: '%env(TIKTOK_CLIENT_KEY)%'
            string $tiktokClientSecret: '%env(TIKTOK_CLIENT_SECRET)%'
            string $tiktokRedirectUri: '%env(TIKTOK_REDIRECT_URI)%'
            string $apiUrl: '%env(API_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Fixtures\Provider\EmailProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\LastnameProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\FirstnameProvider:
        tags: ['nelmio_alice.faker.provider']

    App\Fixtures\Provider\PlainPasswordProvider:
        tags: ['nelmio_alice.faker.provider']

    Aws\S3\S3Client:
        arguments:
            -   version: 'latest'
                region: '%env(S3_REGION)%'
                endpoint: '%env(S3_ENDPOINT)%'
                use_path_style_endpoint: true
                credentials:
                    key: '%env(S3_ACCESS_KEY)%'
                    secret: '%env(S3_SECRET_KEY)%'

    App\Serializer\ValueObjectNormalizer:
        tags: [serializer.normalizer]

    app.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }